var allProducts = <String>[
  "Ajdova kaša",
  "Ajdovi žganci",
  "Albuminska skuta",
  "Alkohol drugo",
  "Ameriške borovnice",
  "Ananas",
  "Arašidi",
  "Arašidovo maslo",
  "Aronija",
  "Avokado",
  "Banane",
  "Bio meso",
  "Blitva",
  "Bob",
  "Bonboni",
  "Borovnice",
  "Brazilski oreščki",
  "Brezglutenski izdelki",
  "Brokoli",
  "Brusnice",
  "Buče",
  "Bučke",
  "Bulgur",
  "Burek",
  "Cikorija",
  "Cvetača",
  "Cvetje rezano",
  "Cvetlični lonci",
  "Čaj drugo",
  "Čaj sadni",
  "Čaj zeliščni",
  "Čebula",
  "Čemaž",
  "Česen",
  "Češnje",
  "Čičerika",
  "Čili",
  "Čili omake",
  "Čips",
  "Čokolada",
  "Čokolada jedilna",
  "Damski vložki",
  "Deodorant",
  "Divjačina",
  "Domači izdelki drugo",
  "Drevesa",
  "Drobtine",
  "Druge sladkarije",
  "Drugi izdelki",
  "Drugi namazi",
  "Drva",
  "Feferon",
  "Feferon pekoči",
  "Feferon sladki",
  "Fige",
  "Fižol",
  "Fižol stročji",
  "Gazirana pijača",
  "Ghee maslo",
  "Gnojila",
  "Gobe",
  "Gobica za pomivanje",
  "Goji",
  "Gomoljna zelena",
  "Gospodinjski pripomočki drugo",
  "Govedina",
  "Grah",
  "Granatno jabolko",
  "Grenivke",
  "Gris",
  "Grisini",
  "Grmičevje",
  "Grozdje",
  "Hrana za mačke",
  "Hrana za ostale živali",
  "Hrana za pse",
  "Hrana za ptiče",
  "Hrana za živali drugo",
  "Hren",
  "Hrenovke",
  "Hruške",
  "Izdelki brez laktoze",
  "Izdelki iz testa drugo",
  "Izdelki iz voska",
  "Jabolka",
  "Jagnjetina",
  "Jagode",
  "Jajca drugo",
  "Jajčevci",
  "Ječmen",
  "Jogurt ",
  "Jogurt drugi",
  "Jogurt kozji",
  "Jogurt kravji",
  "Jogurt ovčji",
  "Josta",
  "Kakav",
  "Kaki",
  "Kalčki",
  "Kava",
  "Kava brezkofeinska",
  "Kava pražena",
  "Kefir",
  "Ketchup",
  "Kis balzamični",
  "Kis druge vrste",
  "Kis jabolčni",
  "Kis vinski",
  "Kis za vlaganje",
  "Kislo mleko",
  "Kitajsko zelje",
  "Kivi",
  "Klobase",
  "Kokice/pokovka",
  "Kokos",
  "Kokos moka",
  "Kokosovo maslo",
  "Kokošja jajca",
  "Koleraba",
  "Kombuča",
  "Kompot",
  "Konoplja drugo",
  "Konopljina semena",
  "Konzervirana mesna hrana",
  "Konzervirana zelenjava",
  "Konzervirane ribe",
  "Konzervirani izdelki drugo",
  "Konzervirano sadje",
  "Korenje",
  "Korenje rumeno",
  "Koromač",
  "Koruza",
  "Kosmulje",
  "Kostanj",
  "Kozmetika drugo",
  "Kozmetika za obraz",
  "Kozmetika za telo",
  "Kreme domače",
  "Kreme drugo",
  "Kreme za dojenčke",
  "Krma",
  "Krompir",
  "Sladki krompir",
  "Krpe",
  "Kruh ajdov",
  "Kruh bel",
  "Kruh črn",
  "Kruh drugo",
  "Kruh polbeli",
  "Kumare",
  "Kuskus",
  "Kutina",
  "Kvas",
  "Kvinoja",
  "Laneno seme",
  "Leča",
  "Lešniki",
  "Lešnikov namaz",
  "Lešnikovo mleko",
  "Likerji",
  "Limete",
  "Limone",
  "Liofilizirano sadje",
  "Listnati ohrovt",
  "Lubenica",
  "Lutenica",
  "Majoneza",
  "Makadamija",
  "Maline",
  "Mandarine",
  "Mandljevo mleko",
  "Mandlji",
  "Mango",
  "Marelice",
  "Margarina",
  "Marmelada",
  "Maslo",
  "Maslo zeliščno",
  "Mast",
  "Matični mleček",
  "Mazila",
  "Med",
  "Melona",
  "Mesni izdelki drugi",
  "Meso drobnice",
  "Meso drugo",
  "Mikrozelenje",
  "Milo",
  "Mlečni izdelki",
  "Mlečni namaz",
  "Mlečni namazi",
  "Mleko brez laktoze",
  "Mleko drugo",
  "Mleko kozje",
  "Mleko kravje",
  "Moka ajdova",
  "Moka brez glutena",
  "Moka druga",
  "Moka konopljina",
  "Moka pirina",
  "Moka polnozrnata",
  "Moka pšenična",
  "Moka riževa",
  "Moka ržena",
  "Morski sadeži",
  "Motovilec",
  "Nadzemna koleraba",
  "Namazi brez glutena",
  "Namazi drugo",
  "Naši",
  "Njoki",
  "Nojeva jajca",
  "Oblačila za odrasle",
  "Ocvirki",
  "Ohrovt",
  "Ohrovt brstični",
  "Olive",
  "Olje bučno",
  "Olje drugo",
  "Olje olivno",
  "Olje rastlinsko",
  "Olje repično",
  "Olje sončnično",
  "Omake drugo",
  "Omake za testenine",
  "Oprema za domače živali",
  "Orehi",
  "Oreščki drugo",
  "Otroška oblačila",
  "Otroška oprema",
  "Otroške plenice",
  "Otroški robčki",
  "Ovčetina",
  "Ovsena kaša",
  "Ovseni kosmiči",
  "Ovseno mleko",
  "Papirnate brisače",
  "Papirnati robčki",
  "Papirnati servieti",
  "Paprika",
  "Paradižnik",
  "Paradižnik češnjev",
  "Pastinak",
  "Pašteta",
  "Pecivo",
  "Pecivo brez glutena",
  "Pehtran",
  "Pekovski izdelki",
  "Peleti",
  "Penine",
  "Perutnina",
  "Peteršilj koren",
  "Peteršilj list, steblo",
  "Pijača drugo",
  "Pinjenec",
  "Pisarniški material",
  "Piškoti",
  "Pite",
  "Pivo",
  "Pivo domače",
  "Pleteni izdelki",
  "Ploščice",
  "Polenta",
  "Poltrajne klobase",
  "Pomaranče",
  "Pomelo",
  "Poper",
  "Por",
  "Posebna prehrana drugo",
  "Potica",
  "Prekajeni mesni izdelki",
  "Prepeličja jajca",
  "Prigrizki drugo",
  "Propolis",
  "Prosena kaša",
  "Rabarbara",
  "Radič",
  "Rastlinski namazi",
  "Rastlinsko maslo",
  "Ravioli",
  "Rdeča pesa",
  "Redkev črna",
  "Redkvica",
  "Regrat",
  "Repa",
  "Repa kisla",
  "Ribe drugo",
  "Ribe morske",
  "Ribe sladkovodne",
  "Ribez",
  "Ringlo",
  "Riževe testenine",
  "Riževo mleko",
  "Robide",
  "Rože v loncih",
  "Rukola",
  "Sadike ostalo",
  "Sadike rož",
  "Sadike začimbnic",
  "Sadike zelenjave",
  "Sadje drugo",
  "Sadje kandirano",
  "Salame",
  "Satje",
  "Semema druga",
  "Semena ostalo",
  "Semena za setev",
  "Senf",
  "Sir",
  "Sir brez laktoze",
  "Sirotka",
  "Sirup",
  "Skuta",
  "Sladkarije drugo",
  "Sladoled",
  "Slani arašidi",
  "Slive",
  "Smetana kisla",
  "Smetana sladka",
  "Smuti",
  "Soda bikarbona",
  "Soja",
  "Sojino mleko",
  "Sok",
  "Sol",
  "Solata",
  "Solata endivja",
  "Sredstvo za pomivanje posode",
  "Stebelna zelena",
  "Suhe začimbe",
  "Suho sadje",
  "Suhomesnati izdelki",
  "Sveče",
  "Sveže ribe",
  "Sveže začimbe",
  "Sveži sir",
  "Svinjina",
  "Šalotka",
  "Šampinjoni",
  "Šetraj",
  "Šparglji",
  "Špinača",
  "Štruklji",
  "Tamponi",
  "Tartufi",
  "Tartufi drugo",
  "Tekstilni izdelki",
  "Teletina",
  "Testenine brez glutena",
  "Testenine brez jajc",
  "Testenine drugo",
  "Testenine z jajci",
  "Toaletni papir",
  "Tofu",
  "Torte",
  "Tortelini",
  "Vata",
  "Vino belo",
  "Vino oranžno",
  "Vino ostalo",
  "Vino rdeče",
  "Vino rose",
  "Višnje",
  "Vrečke za smeti",
  "Vrt drugo",
  "Vrtna oprema",
  "Vrtna zemlja",
  "Vrtno orodje",
  "Začimbe",
  "Začimbe drugo",
  "Začimbne mešanice",
  "Zelena",
  "Zelenjava drugo",
  "Zelenjavni čips",
  "Zelje kislo",
  "Zelje rdeče",
  "Zelje zeleno",
  "Zemlja drugo",
  "Zemlja za roža",
  "Zmrznjena morska",
  "Zmrznjena zelenjava",
  "Zmrznjeni izdelki drugo",
  "Zmrznjeni mesni izdelki",
  "Zmrznjeno sadje",
  "Zobna krtačka",
  "Zobna pasta",
  "Žganje",
  "Žitarice druge",
  "Žižole",
  "Kruh polnozrnat",
  "Jušna zelenjava",
  "Jogurt probiotični",
  "Sir za žar",
  "Mladi sir",
];
